### ISSUE TITLE
Harvest sea ice concentration form OSISAF

### ISSUE THREAD

**Issue by akorosov** [nansencenter/django-geo-spaas-harvesting#16]
OSIAF provides sea ice concentration data over THREDDS here:
https://thredds.met.no/thredds/osisaf/osisaf_seaiceconc.html

There are aggregated datasets which are of lesser interest (e.g.  Aggregated Sea Ice Concentration for the Northern Hemisphere Lambert Projection) and individual daily files in two subfolders:
https://thredds.met.no/thredds/catalog/osisaf/met.no/ice/conc/catalog.html
https://thredds.met.no/thredds/catalog/osisaf/met.no/ice/amsr2_conc/catalog.html

In the subfolders the files are given for two different hemispheres (nh, sh) and  in two different projections (polstere, ease).
In principle we need only data from nh and in polstere projection, so it would be nice if we could select which data to ingest by filename (e.g `ice_conc_nh_polstere*`).

The task is to extend harvesting to manage the sources mentioned above.

It is important to think about extending that in future to also harvest metadata from:
https://thredds.met.no/thredds/osisaf/osisaf_seaicetype.html
and 
https://thredds.met.no/thredds/osisaf/osisaf_seaicedrift.html

**Comment by akorosov** [comment]
```python
class PODAACHarvester(Harvester):
    ingester = ingesters.DDXIngester
    crawler = crawlers.OpenDAPCrawler

    """Harvester class for PODAAC data (NASA)"""
    def _create_crawlers(self):
        return [
            self.crawler(url, time_range=(self.get_time_range()))
            for url in self.config['urls']
        ]

    def _create_ingester(self):
        parameters = {}
        for parameter_name in ['max_fetcher_threads', 'max_db_threads']:
            if parameter_name in self.config:
                parameters[parameter_name] = self.config[parameter_name]
        return self.ingester(**parameters)

class OSISAFHarvester(PODAACHarvester):
    ingester = ingesters.DDXOsisafIngester
    crawler = crawlers.OSISAFCrawler
```

**Comment by akorosov** [comment]
```python
class DDXIngester(MetanormIngester):
    def prepare_ur(self, url):
        return url

    ....
    def _get_normalized_attributes(self, url, *args, **kwargs):
        """Get normalized metadata from the DDX info of the dataset located at the provided URL"""

        prepared_url = url if url.endswith('.ddx') else url + '.ddx'
        prepared_url = self.prepare_url(prepared_url)
        ....

class DDXOsisafIngester(DDXIngester)
    def prepare_url(self, prepared_url):
        return prepared_url.replace(prepared_url[prepared_url.find("catalog/"):prepared_url.find("?dataset=")+9],"dodsC/")

```

**Comment by opsdep** [comment]
The new tests of this should not pass because we need new normalizer of OSISAF for it and it needs new version of metanorm to work correctly. So please merge that one first when it becomes.
@akorosov @aperrin66
