### ISSUE TITLE
harvesting from some of ftp resources

### ISSUE THREAD

**Issue by opsdep** [nansencenter/django-geo-spaas-harvesting#21]
we are going do need a crawler and ingester for FTP repositories.
FTP is really not the most efficient way to get metadata, but sometimes we won't have a choice.
 
The crawler is going to be simple enough, but the ingester is most likely going to have to download each file, extract the metadata and remove the file. Maybe for some repositories we can deduct some information from the name of the file.
 
Here are some examples of data we are going to need from FTP repositories for one of the projects:

	
      GMI L3 from ftp://ftp.remss.com/gmi/bmaps_v08.2/ (registration needed)

	CCI Climatology from ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/data/CDR_v2/Climatology/L4/

	AMSR2 L2: ftp://ftp.gportal.jaxa.jp:/standard/GCOM-W/GCOM-W.AMSR2/L2.SST/3 (registration needed)

**Comment by akorosov** [comment]
ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/data/CDR_v2/Climatology/L4/
pti.get_gcmd_platform('Earth Observation Satellites')
pti.get_gcmd_instrument('Imaging Spectrometers/Radiometers')   
pti.get_gcmd_provider('ESA/CCI')  

time_coverage_start = 1982MMDD where MM DD is date based on day of year: D013
time_coverage_end = 2010MMDD where MM DD is date based on day of year: D013
geographic location = -180, 180, -90, 90 


AMSR2 L2: ftp://ftp.gportal.jaxa.jp:/standard/GCOM-W/GCOM-W.AMSR2/L2.SST/3 (registration needed)
pti.get_gcmd_instrument('AMSR2')    
pti.get_gcmd_platform('GCOM-W1')    
pti.get_gcmd_provider('JP/JAXA/EOC')  
It is impossible to ingest geospatioal metadata  from filename - download of file is needed.
AMSR L3 SST:
ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L3.SST_10/3
It is possible to ingest this data as it is fixed geographical projection (global coverage)
How critical is to ingest L2? Check w Adrien and Sylvain.


GMI L3 from ftp://ftp.remss.com/gmi/bmaps_v08.2/ (registration needed)
pti.get_gcmd_instrument('GMI')    
pti.get_gcmd_platform('GPM')  
pti.get_gcmd_provider('NASA/GSFC/SED/ESD/LA/GPM') 
geographic location = -180, 180, -90, 90
# needs to be checked!
Use software provided here:
http://data.remss.com/gmi/support_v08.1/python/
to read files and find the geographical extent of the dataset.

**Comment by akorosov** [comment]
ftp://ftp.gportal.jaxa.jp:/standard/GCOM-W/GCOM-W.AMSR2/L2.SST/3
ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L3.SST_10/3
ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/data/CDR_v2/Climatology/L4/
pti.get_cf_standard_name('sea_surface_temperature') 


GMI L3 from ftp://ftp.remss.com/gmi/bmaps_v08.2/ (registration needed)
needs to be checked.
Use again this software to get list of variables:
http://data.remss.com/gmi/support_v08.1/python/example_usage.py

**Comment by akorosov** [comment]
Title:

ftp://ftp.gportal.jaxa.jp:/standard/GCOM-W/GCOM-W.AMSR2/L2.SST/3
AMSR2-L2 Sea Surface Temperature

ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L3.SST_10/3
AMSR2-L3 Sea Surface Temperature

GMI L3 from ftp://ftp.remss.com/gmi/bmaps_v08.2/ (registration needed)
Title:
Atmosphere parameters from Global Precipitation Measurement Microwave Imager

Parameters:
pti.get_cf_standard_name('sea_surface_temperature')

Other standard names:
wind_speed

atmosphere_mass_content_of_water_vapor

atmosphere_mass_content_of_cloud_liquid_water

rainfall_rate
