### ISSUE TITLE
remove the temporary solution in ftp harvester!

### ISSUE THREAD

**Issue by opsdep** [nansencenter/django-geo-spaas-harvesting#27]
There is a temporary solution in ftp harvester for setting the entry_id of each dataset. I must be removed and the correct place for the solution is inside the metanorm repo. This related to the issue https://github.com/nansencenter/metanorm/issues/22#issue-695801954

**Comment by aperrin66** [comment]
**duplicate** should be used when an issue describing the same problem already exists in this repository.
**invalid** should be used when the issue itself is invalid (like if an external user makes an invalid issue).
I will take the liberty to remove those tags.
